### ISSUE TITLE
Strict Standards warning

### ISSUE THREAD

**Issue by moraleida** [10up/debug-bar-elasticpress#1]
When used with strict error reporting this generates a warning that can be easily fixed by making the `factory()` method static (or by changing the method call):

```Strict Standards: Non-static method EP_Debug_Bar_ElasticPress::factory() should not be called statically in /path/to/plugin/debug-bar-elasticpress/debug-bar-elasticpress.php on line 19```

**Comment by tlovett1** [comment]
Mind posting a PR?

**Comment by moraleida** [comment]
thanks!
