### ISSUE TITLE
Query log is empty

### ISSUE THREAD

**Issue by colis** [10up/debug-bar-elasticpress#14]
Hi, I'm currently using WP 4.7.2, EP 2.1.2, ES 5.2, EP Debug Bar 1.1.1., `WP DEBUG` set to `true` in wp-config.php

After the execution of a query, I can't see the results on Debug Bar panel and the call to this function

`$queries = ep_get_query_log();`

returns an empty array.

![ep-debug-bar](https://cloud.githubusercontent.com/assets/9059716/22931314/72defbb8-f2c4-11e6-8cc1-0c89ccd9e0e1.png)

**Comment by tlovett1** [comment]
This means ElasticPress executed no queries.

**Comment by colis** [comment]
Weird, 'cause I'm querying Elasticsearch and I get results

**Comment by guy-bouchard** [comment]
Same here, this plugin seems to be broken.

**Comment by tlovett1** [comment]
I would trace down the API calls within ElasticPress. Plugin seems to be working fine for others.

**Comment by robertsheacole** [comment]
The same is happening to me as well. However, when I run `dd(ep_get_query_log());` I get lots of data back. 

How would you recommend going about tracing down the API calls within ElasticPress?

**Comment by robertsheacole** [comment]
I should also say that when I hit the elasticsearch endpoint directly in my browser I get 76 posts back.

**Comment by tlovett1** [comment]
@eugene-manuilov mind taking a look?

**Comment by robertsheacole** [comment]
Thanks @tlovett1!

**Comment by eugene-manuilov** [comment]
Hi @robertsheacole,

did you add `ep_integrate` argument to your queries where you need ElasticPress integration? 

https://github.com/10up/ElasticPress#supported-wp_query-parameters

**Comment by robertsheacole** [comment]
Hey @eugene-manuilov, 

I sure did. I added 'ep_integrate' => true the args being passed into WP_Query.

**Comment by robertsheacole** [comment]
I have looked over the code and don't see where it's saving the query logs in the db. I don't even see an option being saved in my options table.

**Comment by robertsheacole** [comment]
Let me clarify...I do see where it is saving the `ep_query_log` option but I don't see that in my db.

**Comment by eugene-manuilov** [comment]
Hm... that's weird... what plugins do you have activated on your end? Can you try it on a fresh setup? I have checked this on my local and it works for me...

**Comment by robertsheacole** [comment]
Ok, so maybe I'm just silly. I see it working now. I was unaware that I had to view the queries run while on the page that just ran that query. So, I can't run a search and then go to the dashboard and look at the logged queries. 

This seems a bit confusing. Why would we just log them in the db and show that every time you go to the debug bar tool?

**Comment by photocurio** [comment]
where did you find `ep_get_query_log()`?  I'm getting an undefined function error.

**Comment by felipeelia** [comment]
Closing this one out as the `ep_query_log` error was fixed in 2.0.0. Answering @photocurio 's question, the `ep_get_query_log()` method was replaced by `\ElasticPress\Elasticsearch::factory()->get_query_log()` in newer versions of ElasticPress.
