### ISSUE TITLE
Base Panel class is now an abstract. DB-EP is missing init() functions.

### ISSUE THREAD

**Issue by crazyjaco** [10up/debug-bar-elasticpress#18]
New development for the Debug Bar plugin happens in:
http://github.com/dd32/debug-bar

A commit was made on August 29th, 2017 that changed the Panel class to be an abstract and also labeled the `init` and `render` methods as abstract as well.

As a result, the `EP_Debug_Bar_ElasticPress` class now throws a fatal error because it does not have an `init` method.

**Comment by tlovett1** [comment]
How's that look?

**Comment by crazyjaco** [comment]
Oh wow. You made the change for this so quick I thought the email was for the issue submission I made. This looks good to me at a glance. Are you able to activate with the latest debug bar version? I believe that was when I was getting the fatal error.

**Comment by felipeelia** [comment]
Closing this one as it was fixed in b7439d3.
