### ISSUE TITLE
Add helper text to assist debugging no queries

### ISSUE THREAD

**Issue by nathanielks** [10up/debug-bar-elasticpress#23]
Hi team!

I was debugging the absence of queries being listed the other day and @johnbillion prompted me to share my findings here. While I was debugging, it would have been awesome if there was a help/informational message on the ElasticPress Debug Bar tab noting two important reasons why queries might not be showing up: 
-  Debugging constants not being set
- ElasticPress is currently indexing

Our issue was a combination of the two: I discovered we hadn't set `WP_DEBUG` or `WP_EP_DEBUG` and indexing was currently paused in WP Admin, which short circuited the WP_Query integration. I added a debugging constant and unpaused indexing and all was well. It would have been really helpful if there were some help text in the ElasticPress Debug Bar panel checking these two events, something like:

> WP_DEBUG or WP_EP_DEBUG must be enabled for queries to be logged. If queries still aren't showing up, click here to troubleshoot

It could have a page listing other reasons why queries might not be showing up, and/or status indicators saying 

- ✅ `WP_EP_DEBUG` is defined
- ⚠️ Indexing is currently paused, so queries will not show up

Thank you for all your hard work!

**Comment by jeffpaul** [comment]
@nathanielks thanks for the feedback, it's greatly appreciated!  Would you be open to submitting a PR to help resolve this as well?
