### ISSUE TITLE
CSS loaded in all requests

### ISSUE THREAD

**Issue by cbratschi** [10up/debug-bar-elasticpress#26]
**Describe the bug**

The Debug Bar ElasticPress CSS file should only be loaded for admin users and not be loaded by all users.

**Steps to Reproduce**

Check HTML source code for the CSS file.

**Expected behavior**

**Screenshots**

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - WordPress version: 
 
 - Plugins and version: 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by felipeelia** [comment]
It's been a while @cbratschi and I'm not able to reproduce this anymore using 2.0.0. Can you please confirm? Thanks!

**Comment by cbratschi** [comment]
@felipeelia it is still loaded on all pages:

CSS:

```
<link rel='stylesheet' id='debug-bar-elasticpress-css'  href='https://xyz.ch/wp-content/plugins/debug-bar-elasticpress/classes/../assets/css/main.css?ver=2.0.0' type='text/css' media='all' />
```

JS:

```
<script type='text/javascript' src='https://xyz.ch/wp-content/plugins/debug-bar-elasticpress/classes/../assets/js/main.js?ver=2.0.0' id='debug-bar-elasticpress-js'></script>
```

**Comment by felipeelia** [comment]
@cbratschi just to confirm, which version of Debug Bar and Debug Bar EP are you using? Also, is there happening on a site that is public somewhere? Thanks!

**Comment by cbratschi** [comment]
@felipeelia the following versions are used (the latest ones):

Query Monitor: 3.7.1
Debug Bar EP: 2.0.0

You can reproduce it here:

https://telebasel.ch/
