### ISSUE TITLE
Use <xmp> for displaying JSON results instead of <pre>

### ISSUE THREAD

**Issue by kingkool68** [10up/debug-bar-elasticpress#3]
Ah the long forgotten `<xmp>` element. It would be much better to use in the case for showing JSON responses from Elasticsearch because it treats markup as literal text. From the sitepoint reference: http://reference.sitepoint.com/html/xmp

> Unlike pre, xmp element treats markup characters as literal text. This makes xmp useful for development - e.g.for testing output from PHP that may contain markup, where you want to see the markup as code.

I'm working on a site with some cruddy markup in the post_content so looking at the query result comes out like this https://cloudup.com/ctgszL4-2Nc

**Comment by eugene-manuilov** [comment]
@tlovett1 I have made some readability improvements. Could you please check #4 PR?

**Comment by tlovett1** [comment]
Merged #4. Happy to review another one for `xmp`

**Comment by eugene-manuilov** [comment]
`xmp` is not needed anymore, plus it is obsoleted element and not recommended to use.
