### ISSUE TITLE
Better spacing when used with Query Monitor

### ISSUE THREAD

**Issue by felipeelia** [10up/debug-bar-elasticpress#62]
### Is your enhancement related to a problem? Please describe.

Although this plugin is meant to be used with Debug Bar, it is also compatible with Query Monitor, with the only downside of some weird spacing in its panel.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MARQAS** [comment]
The styling for this was added via: https://github.com/10up/debug-bar-elasticpress/pull/63/commits/206fef4eda5697e8db7b33b3837e301622b59366
