### ISSUE TITLE
No option in Query Monitor Panel when Jetpack is activated. 

### ISSUE THREAD

**Issue by burhandodhy** [10up/debug-bar-elasticpress#77]
### Describe the bug

When the Jetpack is activated, ElasticPress option doesn't rendered in the Query Monitor Bar.

### Steps to Reproduce

1. Activate the Jetpack
2. Go to Frontend and search any term
3. There is no option ElasticPress option in the Query Monitor panel

<img width="193" alt="image" src="https://github.com/10up/debug-bar-elasticpress/assets/7139602/7dfff38d-f0c8-4215-a354-a6d42cbfc368">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
As Query Monitor has many more active installations than Debug Bar, if https://github.com/johnbillion/query-monitor/pull/810 isn't merged we can study the possibility of making Debug Bar ElasticPress fully compatible with QM.
