### ISSUE TITLE
Provide an easy way to see how a document is indexed

### ISSUE THREAD

**Issue by felipeelia** [10up/debug-bar-elasticpress#78]
### Is your enhancement related to a problem? Please describe.

ElasticPress 4.7.0 has a new WP-CLI command (`wp elasticpress get post <id>`) that makes it easier to check how a document is indexed in Elasticsearch. It would be great if we could provide something like that in Debug Bar EP as well, so people don't need access to WP-CLI to check it.

### Describe alternatives you've considered

We could add a new button to trigger that. We already have "hidden" parameters like `explain` that, if added to the query string, makes ES explain the query. Nobody uses that because it is not documented anywhere obvious and also, we don't expose that in any way on the screen. Perhaps a new section with buttons like `Explain queries` and `Query document from ES`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by burhandodhy** [comment]
Use `Reload and retrieve raw ES document` instead of `Query document from ES` for button
