### ISSUE TITLE
PHP Notice

### ISSUE THREAD

**Issue by allan23** [10up/debug-bar-elasticpress#8]
Browsing around the wp-admin, the following PHP notice pops up in error logs:

PHP Notice:  Undefined index: body in /classes/class-ep-debug-bar-elasticpress.php on line 102

**Comment by tlovett1** [comment]
@allan23 is this still happening?

**Comment by r66r** [comment]
It seems this plugin has another problem:

Undefined index: method in /.../debug-bar-elasticpress/classes/class-ep-debug-bar-elasticpress.php on line 101

My environment:
- WordPress: 4.5.3
- ElasticPress: 2.0
- Debug bar: 0.8.4
- Debug bar ElasticPress: 1.0

**Comment by jeffpaul** [comment]
@allan23 @r66r are either of you still seeing this issue?

**Comment by r66r** [comment]
@jeffpaul In my case, with everything updated (PHP 7.2, WP 5.3, Debug Bar 1.0, Debug Bar ElasticPress 1.4), the issue is no longer relevant.
